# Generated by Django 4.2.2 on 2023-06-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Skill name')),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('text', models.TextField(verbose_name='About me text')),
                ('skills', models.ManyToManyField(related_name='skills', to='main.skills')),
            ],
            options={
                'verbose_name': 'about',
                'verbose_name_plural': 'About me',
            },
        ),
    ]
