# Generated by Django 4.2.2 on 2023-06-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='short_info',
            field=models.TextField(blank=True, max_length=3000, verbose_name='Short text about me'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='text',
            field=models.TextField(verbose_name='Full text about me'),
        ),
    ]
