# Generated by Django 4.2.2 on 2023-06-10 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_technologies_projects_projectoverviewtextparts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectoverviewtextparts',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_overview_parts', to='main.projects', verbose_name='Project instance'),
        ),
    ]
